// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIerm-Iynw2qWsR_7DT9_4MfMQrS0ojQQ',
    appId: '1:804851390316:web:30b8fc7b6bb88dff85c549',
    messagingSenderId: '804851390316',
    projectId: 'movie-clone-cba67',
    authDomain: 'movie-clone-cba67.firebaseapp.com',
    storageBucket: 'movie-clone-cba67.firebasestorage.app',
    measurementId: 'G-8CNYCX8GC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-s0-3TCOl94p6RgNNXfz8u7M7M_tJ3WM',
    appId: '1:804851390316:android:123cf9b7bcee686985c549',
    messagingSenderId: '804851390316',
    projectId: 'movie-clone-cba67',
    storageBucket: 'movie-clone-cba67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-r3_p9Zrhvh5D_URhtAbTQVVd-zLQdXE',
    appId: '1:804851390316:ios:f81993bf6e83acbd85c549',
    messagingSenderId: '804851390316',
    projectId: 'movie-clone-cba67',
    storageBucket: 'movie-clone-cba67.firebasestorage.app',
    iosBundleId: 'com.example.movieapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-r3_p9Zrhvh5D_URhtAbTQVVd-zLQdXE',
    appId: '1:804851390316:ios:f81993bf6e83acbd85c549',
    messagingSenderId: '804851390316',
    projectId: 'movie-clone-cba67',
    storageBucket: 'movie-clone-cba67.firebasestorage.app',
    iosBundleId: 'com.example.movieapps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIerm-Iynw2qWsR_7DT9_4MfMQrS0ojQQ',
    appId: '1:804851390316:web:9b6ba52bfcdce04f85c549',
    messagingSenderId: '804851390316',
    projectId: 'movie-clone-cba67',
    authDomain: 'movie-clone-cba67.firebaseapp.com',
    storageBucket: 'movie-clone-cba67.firebasestorage.app',
    measurementId: 'G-7VJR7T2YKV',
  );
}
